### ISSUE TITLE
API errors, is this the reason I cannot create an account?

### ISSUE THREAD

**Issue by kenjibailly** [solution-libre/docker-socioboard#5]
https://192.168.xx.xx:3000 doesn't load as in "site can't be reached".
3001 - 3004 can be reached, but give a blank page

Docker api container errors:

```
3|notify.server  | Mysql database connected
3|notify.server  | Mongo Database has been connected.
3|notify.server  | service listening on http://localhost:3004 with development Environment!
1|feeds.server   | Mysql database connected
1|feeds.server   | Mongo Database has been connected.
1|feeds.server   | service listening on http://localhost:3001 with development Environment!
2|publish.server | Error: 
2|publish.server |  Error on Day wise Scheduler 
2|publish.server |  Unknown column 'start_date' in 'field list'
2|publish.server |     at ScheduleLibs.startDaywiseSchedule (file:///opt/socioboard-api/Publish/core/schedule/schedule-base.js:154:13)
2|publish.server |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2|publish.server | Unhandled Rejection:  Error: 
2|publish.server |  Error on Day wise Scheduler 
2|publish.server |  Unknown column 'start_date' in 'field list'
2|publish.server |     at ScheduleLibs.startDaywiseSchedule (file:///opt/socioboard-api/Publish/core/schedule/schedule-base.js:154:13)
2|publish.server |     at processTicksAndRejections (node:internal/process/task_queues:96:5) Promise Promise {
2|publish.server |   <rejected> Error: 
2|publish.server |    Error on Day wise Scheduler 
2|publish.server |    Unknown column 'start_date' in 'field list'
2|publish.server |       at ScheduleLibs.startDaywiseSchedule (file:///opt/socioboard-api/Publish/core/schedule/schedule-base.js:154:13)
2|publish.server |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
2|publish.server | }
2|publish.server | Error: 
2|publish.server |  Error on One time Scheduler 
2|publish.server |  SequelizeDatabaseError: Unknown column 'start_date' in 'field list'
2|publish.server |     at ScheduleLibs.startTodaySchedule (file:///opt/socioboard-api/Publish/core/schedule/schedule-base.js:223:13)
2|publish.server |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2|publish.server | Unhandled Rejection:  Error: 
2|publish.server |  Error on One time Scheduler 
2|publish.server |  SequelizeDatabaseError: Unknown column 'start_date' in 'field list'
2|publish.server |     at ScheduleLibs.startTodaySchedule (file:///opt/socioboard-api/Publish/core/schedule/schedule-base.js:223:13)
2|publish.server |     at processTicksAndRejections (node:internal/process/task_queues:96:5) Promise Promise {
2|publish.server |   <rejected> Error: 
2|publish.server |    Error on One time Scheduler 
2|publish.server |    SequelizeDatabaseError: Unknown column 'start_date' in 'field list'
2|publish.server |       at ScheduleLibs.startTodaySchedule (file:///opt/socioboard-api/Publish/core/schedule/schedule-base.js:223:13)
2|publish.server |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
2|publish.server | }
2|publish.server | Error: 
2|publish.server |  Error on One time Scheduler 
2|publish.server |  SequelizeDatabaseError: Unknown column 'start_date' in 'field list'
2|publish.server |     at ScheduleLibs.startTodaySchedule (file:///opt/socioboard-api/Publish/core/schedule/schedule-base.js:223:13)
2|publish.server |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2|publish.server | Error: 
2|publish.server |  Error on Day wise Scheduler 
2|publish.server |  Unknown column 'start_date' in 'field list'
2|publish.server |     at ScheduleLibs.startDaywiseSchedule (file:///opt/socioboard-api/Publish/core/schedule/schedule-base.js:154:13)
2|publish.server |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2|publish.server | Unhandled Rejection:  Error: 
2|publish.server |  Error on One time Scheduler 
2|publish.server |  SequelizeDatabaseError: Unknown column 'start_date' in 'field list'
2|publish.server |     at ScheduleLibs.startTodaySchedule (file:///opt/socioboard-api/Publish/core/schedule/schedule-base.js:223:13)
2|publish.server |     at processTicksAndRejections (node:internal/process/task_queues:96:5) Promise Promise {
2|publish.server |   <rejected> Error: 
2|publish.server |    Error on One time Scheduler 
2|publish.server |    SequelizeDatabaseError: Unknown column 'start_date' in 'field list'
2|publish.server |       at ScheduleLibs.startTodaySchedule (file:///opt/socioboard-api/Publish/core/schedule/schedule-base.js:223:13)
2|publish.server |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
2|publish.server | }
2|publish.server | Unhandled Rejection:  Error: 
2|publish.server |  Error on Day wise Scheduler 
2|publish.server |  Unknown column 'start_date' in 'field list'
2|publish.server |     at ScheduleLibs.startDaywiseSchedule (file:///opt/socioboard-api/Publish/core/schedule/schedule-base.js:154:13)
2|publish.server |     at processTicksAndRejections (node:internal/process/task_queues:96:5) Promise Promise {
2|publish.server |   <rejected> Error: 
2|publish.server |    Error on Day wise Scheduler 
2|publish.server |    Unknown column 'start_date' in 'field list'
2|publish.server |       at ScheduleLibs.startDaywiseSchedule (file:///opt/socioboard-api/Publish/core/schedule/schedule-base.js:154:13)
2|publish.server |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
2|publish.server | }
```

Might this the reason be that I cannot create an account mentioned here (fixed the regex):
https://github.com/socioboard/Socioboard-5.0/issues/359

I'm thinking this, because I'm getting this error in the web container storage/logs/laravel.log:

```
[2022-04-12 21:00:29] local.INFO: Exception 210 => Function Name =>  => code =>0 => message =>  cURL error 6: Could not resolve host: api (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://api:3000/v1/otp/get-otp-phone-number?countryCode=%2B32&phoneNumber=495123456  
```

Help would be appreciated, been trying to figure this out for quite some time now :)

**Comment by FlorentPoinsaut** [comment]
Hi,
I see that you use an IP (192.168.xx.xx) to web interface access.
~~The log laravel log return a not resolve host. Could you confirm that the "api" domain is resolved by 192.168.xx.xx ?
If not, you have to add this resolution or set the api domain to 192.168.xx.xx.~~

**Comment by kenjibailly** [comment]
> Hi, I see that you use an IP (192.168.xx.xx) to web interface access. The log laravel log return a not resolve host. Could you confirm that the "api" domain is resolved by 192.168.xx.xx ? If not, you have to add this resolution or set the api domain to 192.168.xx.xx.

Thank you so much for your reply!
Not entirely understood, sorry for that.
I was just trying to use the ip that I have exposed the ports from in my docker-compose just to test, didn't know this had to be configured somewhere to have web access.

What I see in my configs is this though and apparently I made a mistake since I renamed "api" to "socioboard_api":
```
APP_URL=https://socioboard.mindglowing.art/
WEBSITE_TITLE="SocioBoard5.0"
API_URL=http://api:3000/
API_URL_FEEDS=http://api:3001/
API_URL_PUBLISH=http://api:3002/
API_URL_UPDATE=http://api:3003/
```

So I replace api above with socioboard_api and I'm getting new errors in the laravel log:

```
[2022-04-13 12:19:56] local.INFO: Exception 210 => Function Name =>  => code =>0 => message =>  cURL error 7: Failed to connect to socioboard_api port 3000: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://socioboard_api:3000/v1/otp/get-otp-phone-number?countryCode=%2B32&phoneNumber=495712572  
[2022-04-13 12:20:25] local.INFO: Exception 210 => Function Name =>  => code =>0 => message =>  cURL error 7: Failed to connect to socioboard_api port 3000: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://socioboard_api:3000/v1/otp/get-otp-phone-number?countryCode=%2B32&phoneNumber=495712572  
```

I also saw that you mentioned this:
> Register a domain like 'socioboard.domain.tld' and theese subdomains 'api-00.socioboard.domain.tld', 'api-01.socioboard.domain.tld', 'api-02.socioboard.domain.tld', 'api-03.socioboard.domain.tld'.

I unfortunately wasn't able to make it work using reverse proxy using this format api.socioboard.domain.ltd
I do however have my socioboard.domain.com working. Adding another subdomain to it, doesn't work.

Is this what I need to do?

**Comment by FlorentPoinsaut** [comment]
My apologies, I wrote an error.
Could you please confirm that the API container is up and running by the command `docker ps`?

**Comment by kenjibailly** [comment]
> My apologies, I wrote an error. Could you please confirm that the API container is up and running by the command `docker ps`?

It's running:
![image](https://user-images.githubusercontent.com/9883910/163186298-fb21e895-7742-44b3-a6de-be2efd36cbe8.png)

With errors, posted those errors in the first message.
Here's a txt file with the logs of the api container
[_socioboard_api_logs (4).txt](https://github.com/solution-libre/docker-socioboard/files/8481661/_socioboard_api_logs.4.txt)

**Comment by FlorentPoinsaut** [comment]
OK.
Are your "web" and "api" services in the same network?

**Comment by kenjibailly** [comment]
API container:
![image](https://user-images.githubusercontent.com/9883910/163191017-35cc2b21-1523-4d46-afba-45fd7b6ab6d5.png)


Web container:
![image](https://user-images.githubusercontent.com/9883910/163191096-5deb6966-677a-4603-8848-950e4c1b7f2f.png)


That means, yes

**Comment by kenjibailly** [comment]
I've tried another several hours, but unfortunately I haven't been able to change anything.
I restarted from the beginning, deleted all my files / images / containers and tried not to change anything, but the .env's and reverse proxy stuff.
This time I kept the docker-compose api and web name instead of renaming them to socioboard_web and socioboard_api.
I only removed the volumes at the bottom and put the paths under the volumes: where needed

I'm getting the same errors though. 
Also still can't make an account, no idea how to bypass the OTP. 
Any idea how to create an account without the OTP (sms)?

Perhaps from there I could see more happening...
